services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=angi_db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_script:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=angi_db
      - RETRY_ATTEMPTS=5
      - RETRY_DELAY=5
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure:5

volumes:
  mysql_data: 

networks:
  app-network:
    driver: bridge
