USE angi_db;

-- Insert data into District
-- Batch 1
INSERT INTO District (district_id, district_name) VALUES
(19, 'quận bình thạnh'),
(28, 'quận 2'),
(32, 'quận 1'),
(2, 'thành phố thủ đức'),
(27, 'quận 3'),
(25, 'quận 5'),
(8, 'quận phú nhuận'),
(18, 'quận bình tân'),
(15, 'quận gò vấp'),
(31, 'quận 10'),
(26, 'quận 4'),
(23, 'quận 7'),
(29, 'quận 12'),
(30, 'quận 11'),
(24, 'quận 6'),
(22, 'quận 8'),
(6, 'quận tân bình'),
(21, 'quận 9'),
(5, 'quận tân phú'),
(12, 'quận hoàng mai'),
(7, 'quận thanh xuân'),
(20, 'quận ba đình'),
(16, 'quận cầu giấy'),
(3, 'quận đống đa'),
(14, 'quận hai bà trưng'),
(13, 'quận hoàn kiếm'),
(4, 'quận tây hồ'),
(11, 'quận hà đông'),
(10, 'quận long biên'),
(9, 'quận nam từ liêm'),
(17, 'quận bắc từ liêm'),
(52, 'huyện bình chánh'),
(46, 'huyện hóc môn'),
(38, 'huyện thanh trì'),
(47, 'huyện hoài đức'),
(43, 'huyện nhà bè'),
(36, 'huyện thạch thất'),
(48, 'huyện gia lâm'),
(40, 'huyện sóc sơn'),
(49, 'huyện củ chi'),
(50, 'huyện cần giờ'),
(45, 'huyện mê linh'),
(35, 'huyện đan phượng'),
(53, 'huyện ba vì'),
(34, 'huyện đông anh'),
(1, 'thị xã sơn tây'),
(44, 'huyện mỹ đức'),
(42, 'huyện phúc thọ'),
(37, 'huyện thường tín'),
(51, 'huyện chương mỹ'),
(41, 'huyện quốc oai'),
(33, 'huyện ứng hòa'),
(39, 'huyện thanh oai');